// Synthesized Foley and machine ambience, activated only by a user gesture.
export function createAudio(){
 let ctx,master,noiseBuffer,loops=[],enabled=false,nextBubble=0;
 function init(){if(ctx)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;ctx=new AC();master=ctx.createGain();master.gain.value=.55;master.connect(ctx.destination);noiseBuffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);let d=noiseBuffer.getChannelData(0);let low=0;for(let i=0;i<d.length;i++){low=(low+Math.random()*.08-.04)*.97;d[i]=Math.random()*.65-.325+low}
  for(let [hz,type,cut] of [[48,'sine',100],[90,'noise',350],[160,'noise',1300]]){let src=type==='noise'?ctx.createBufferSource():ctx.createOscillator();if(type==='noise'){src.buffer=noiseBuffer;src.loop=true}else src.frequency.value=hz;let filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=cut;let gain=ctx.createGain();gain.gain.value=0;src.connect(filter);filter.connect(gain);gain.connect(master);src.start();loops.push(gain)}
 }
 function enable(value){enabled=value;try{init();if(ctx){ctx.resume().catch(()=>{});master.gain.setTargetAtTime(value?.55:0,ctx.currentTime,.1)}}catch{enabled=false}return enabled&&!!ctx}
 function tone(f,end,d=.15,v=.08,type='sine',delay=0){if(!enabled||!ctx)return;let t=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+d);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(v,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(master);o.start(t);o.stop(t+d+.02)}
 function noise(duration,volume,cut=800,delay=0){if(!enabled||!ctx)return;let t=ctx.currentTime+delay,s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();s.buffer=noiseBuffer;f.type='lowpass';f.frequency.value=cut;g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(volume,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+duration);s.connect(f);f.connect(g);g.connect(master);s.start(t,Math.random());s.stop(t+duration+.02)}
 function action(name){if(name==='step'){noise(.15,.24,450);tone(92,38,.1,.13)}else if(name==='water'){noise(1.1,.19,4300);for(let i=0;i<9;i++)tone(500+Math.random()*600,220,.09,.03,'sine',i*.1)}else if(name==='plant'){noise(.25,.24,1800);noise(.2,.16,950,.12)}else if(name==='harvest'){noise(.4,.19,3500);tone(380,620,.13,.045)}else if(name==='ferment'){tone(190,55,.18,.2);noise(.25,.1,550);tone(460,190,.12,.09,'sine',.18)}else if(name==='distill'){noise(.6,.14,1500);tone(100,45,.35,.15)}else if(name==='sell'){for(let i=0;i<4;i++)tone(1100+i*270,850+i*180,.22,.065,'triangle',i*.085)}else if(name==='upgrade'||name==='expand'){for(let i=0;i<3;i++){noise(.08,.23,1700,i*.15);tone(700,210,.15,.07,'triangle',i*.15)}}else if(name==='complete'){[440,550,660].forEach((f,i)=>tone(f,f,.25,.05,'sine',i*.12))}else tone(480,320,.06,.03)}
 function update(state,pos,time){if(!ctx||!enabled)return;const dist=(x,z)=>1/(1+Math.hypot(pos.x-x,pos.z-z)*.6);loops[0].gain.setTargetAtTime(.025,ctx.currentTime,.3);loops[1].gain.setTargetAtTime(state.ferment?.12*dist(4.5,-3.5):0,ctx.currentTime,.3);loops[2].gain.setTargetAtTime(state.still?.16*dist(13,-2):0,ctx.currentTime,.3);if(state.ferment&&time>nextBubble){nextBubble=time+.4+Math.random()*.6;tone(220+Math.random()*200,65,.16,.11*dist(4.5,-3.5))}}
 document.addEventListener('visibilitychange',()=>{if(ctx&&master)master.gain.setTargetAtTime(enabled&&!document.hidden?.55:0,ctx.currentTime,.1)});
 return {enable,action,update};
}
