export function createCareer({state,production,beds,crops,notify,fx,clock=()=>Date.now()}){
 const data={irrigation:false,soil:false,ageJob:null,aged:[],contracts:0};const key='night-harvest-estate-v1';let saveIssue=false;
 function growTime(type){return Math.round(crops[type].time*(data.irrigation?.8:1))}
 function water(b){b.watered=true;b.start=clock();b.duration=growTime(b.type);b.yield=data.soil?4:3}
 function ageProgress(){let j=data.ageJob;if(!j)return {percent:0,remaining:0,ready:false};return {percent:Math.min(100,Math.floor((clock()-j.start)/j.duration*100)),remaining:Math.max(0,Math.ceil((j.start+j.duration-clock())/1000)),ready:clock()>=j.start+j.duration}}
 function contract(){let i=data.contracts,type=['corn','barley','grape'][i%3],quantity=3+Math.min(3,Math.floor(i/3))*3;return {type,quantity,name:['Le bar du quartier','La cave des docks','Le restaurant de nuit'][i%3],reward:Math.round(crops[type].value*quantity*1.45)}}
 function action(a){if(a==='irrigation'||a==='soil'){let cost=a==='irrigation'?180:120;if(data[a]||state.money<cost)return false;state.money-=cost;data[a]=true;notify(a==='irrigation'?'Irrigation installée : arrosage automatique et croissance accélérée.':'Terreau enrichi : les prochaines plantations donnent 4 récoltes.');fx('upgrade');return true}
 if(a==='ageStart'){if(data.ageJob||state.bottles.length<3)return false;data.ageJob={types:state.bottles.splice(0,Math.min(6,state.bottles.length)),start:clock(),duration:45000,notified:false};notify('Vieillissement lancé · 45 secondes');fx('ferment');return true}
 if(a==='ageCollect'){if(!data.ageJob||!ageProgress().ready)return false;data.aged.push(...data.ageJob.types);data.ageJob=null;notify('Bouteilles vieillies récupérées · valeur ×1,5');fx('complete');return true}
 if(a==='contract'){const c=contract();if(state.bottles.filter(k=>k===c.type).length<c.quantity)return false;let n=c.quantity;state.bottles=state.bottles.filter(k=>k===c.type&&n>0?(n--,false):true);state.money+=c.reward;state.sold+=c.quantity;data.contracts++;notify('Commande livrée · +'+c.reward+' $');fx('sell');return true}return false}
 function sellAged(){if(!data.aged.length)return 0;const value=data.aged.reduce((v,k)=>v+Math.round(crops[k].value*1.5),0);state.money+=value;state.sold+=data.aged.length;data.aged=[];return value}
 function tick(){if(data.ageJob&&ageProgress().ready&&!data.ageJob.notified){data.ageJob.notified=true;notify('Le chai est à 100 % · récupérez vos bouteilles vieillies');fx('complete')}}
 function save(){try{localStorage.setItem(key,JSON.stringify({version:1,state:{money:state.money,sold:state.sold,inventory:state.inventory,mash:state.mash,bottles:state.bottles,expanded:state.expanded},units:production.units,beds:beds.map(({type,watered,start,locked,duration,yield:y})=>({type,watered,start,locked,duration,yield:y})),data}));return true}catch{if(!saveIssue){notify('Sauvegarde indisponible dans ce navigateur.');saveIssue=true}return false}}
 function restore(){try{const v=JSON.parse(localStorage.getItem(key));if(!v||v.version!==1||!Array.isArray(v.beds)||v.beds.length!==beds.length)return false;const validList=a=>Array.isArray(a)&&a.length<=10000&&a.every(k=>Object.hasOwn(crops,k));const job=j=>j===null||(j&&validList(j.types)&&Number.isFinite(j.start)&&Number.isFinite(j.duration)&&j.duration>0);if(!v.state||!Number.isFinite(v.state.money)||v.state.money<0||!Number.isFinite(v.state.sold)||!validList(v.state.mash)||!validList(v.state.bottles)||!v.data||!validList(v.data.aged)||!job(v.data.ageJob))return false;for(const k of Object.keys(crops))if(!Number.isInteger(v.state.inventory?.[k])||v.state.inventory[k]<0)return false;for(const kind of ['ferment','still'])if(!Array.isArray(v.units?.[kind])||v.units[kind].length!==3||v.units[kind].some(u=>!job(u.job)))return false;if(v.beds.some(b=>b.type!==null&&!Object.hasOwn(crops,b.type)))return false;Object.assign(state,v.state);for(let i=0;i<beds.length;i++)Object.assign(beds[i],v.beds[i]);for(const kind of ['ferment','still'])production.units[kind].forEach((u,i)=>{const src=v.units[kind][i];u.owned=i===0||!!src.owned;u.upgraded=!!src.upgraded;u.job=src.job});Object.assign(data,v.data);return true}catch{return false}}
 return {data,water,growTime,ageProgress,contract,action,sellAged,tick,save,restore};
}
