import * as T from './three.module.js';
import {buildDetailedPlant,improveWorkshop,disposePlant} from './models.js';
import {createAudio} from './audio.js';
import {createProduction,catalog} from './production.js';
import {expandWorkshop} from './expansion.js';
import {buildEstate} from './estate.js';
import {createCareer} from './career.js';
import {createNavigation} from './navigation.js';
let navigation=null,production=null,expansion=null,estate=null,career=null;let saveTimer=0;let panelHTML='',panelPointerDown=false;const sounds=createAudio();
const $=s=>document.querySelector(s), canvas=$('#world');
let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'})}catch(e){$('#objective').textContent='Votre navigateur ne peut pas lancer la 3D. Activez l’accélération graphique.';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;
const scene=new T.Scene();scene.background=new T.Color('#09171d');scene.fog=new T.FogExp2('#09171d',.024);const camera=new T.PerspectiveCamera(39,innerWidth/innerHeight,.1,150);
let azimuth=.76,elevation=.77,distance=34;const target=new T.Vector3(3,.2,0);function cam(){camera.position.set(target.x+Math.sin(azimuth)*Math.cos(elevation)*distance,Math.sin(elevation)*distance,Math.cos(azimuth)*Math.cos(elevation)*distance);camera.lookAt(target)}cam();
scene.add(new T.HemisphereLight(0xbde7ef,0x253227,2.4));const sun=new T.DirectionalLight(0xd0e8f2,3);sun.position.set(-5,12,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-13,right:13,top:13,bottom:-13});sun.shadow.bias=-.0005;scene.add(sun);
const M={};function mat(c,metal=0,rough=.7){return new T.MeshStandardMaterial({color:c,metalness:metal,roughness:rough})}M.concrete=mat('#334a4d');M.edge=mat('#182a31');M.wall=mat('#253a40');M.wood=mat('#654332');M.soil=mat('#302722');M.metal=mat('#59777b',.6,.4);M.dark=mat('#182d33',.5);M.copper=mat('#bb7842',.7,.32);M.blue=mat('#285577',.5,.42);M.green=mat('#3f7649');M.leaf=mat('#74a052');M.gold=mat('#d0aa51');M.glass=mat('#4a7860',.2,.22);M.black=mat('#172127');
function mesh(geo,m,x=0,y=0,z=0,parent=scene){let o=new T.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}function box(w,h,d,m,x,y,z,p){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,p)}function cyl(rt,rb,h,m,x,y,z,p){return mesh(new T.CylinderGeometry(rt,rb,h,24),m,x,y,z,p)}function sphere(r,m,x,y,z,p){return mesh(new T.SphereGeometry(r,20,14),m,x,y,z,p)}function group(x,y,z){const g=new T.Group();g.position.set(x,y,z);scene.add(g);return g}
function pipe(points,r,m,parent=scene){let c=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)));return mesh(new T.TubeGeometry(c,32,r,8,false),m,0,0,0,parent)}
function textSprite(text,x,y,z,color='#dac190',size=1.5){const c=document.createElement('canvas');c.width=1024;c.height=128;let ctx=c.getContext('2d');ctx.font='600 54px monospace';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,512,82);let tx=new T.CanvasTexture(c),sp=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true,depthWrite:false}));sp.position.set(x,y,z);sp.scale.set(size*4,size*.5,1);scene.add(sp);return sp}
function neon(x,y,z,w,color){let m=new T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:5});box(w,.04,.05,m,x,y,z);let l=new T.PointLight(color,15,8,2);l.position.set(x,y-.15,z+.4);scene.add(l)}
box(17,.65,12,M.edge,0,-.55,0);box(16.7,.17,11.7,M.concrete,0,-.14,0);box(17,.12,.17,M.metal,0,-.05,5.9);box(.17,.12,12,M.metal,-8.4,-.05,0);box(17,4.7,.2,M.wall,0,2.15,-5.9);box(.2,4.7,7.4,M.wall,-8.4,2.15,-2.3);
// Brick seams, structural steel, windows, and overhead practical lights.
for(let i=0;i<10;i++){box(16.6,.014,.012,M.edge,0,i*.45,-5.785);for(let j=0;j<14;j++)box(.014,.43,.013,M.edge,-8+j*1.25+(i%2)*.6,i*.45+.22,-5.78)}
for(let x of [-8,-2,4,8]){box(.16,4.8,.22,M.dark,x,2.2,-5.66);box(.3,.15,.6,M.metal,x,4.35,-5.4)}
for(let x of [-5.9,-3.7]){box(1.6,1.8,.09,M.black,x,2.9,-5.72);box(1.4,1.6,.04,mat('#315064',.5),x,2.9,-5.65);box(.05,1.65,.07,M.metal,x,2.9,-5.6);box(1.45,.05,.07,M.metal,x,2.9,-5.6)}
neon(-4.6,4.1,-5.4,4,0x7eead2);neon(3.6,4.1,-5.4,4,0xffb35d);textSprite('N I G H T   H A R V E S T',2.7,3.35,-5.55,'#e8bb7c',1.6);
for(let x=-7;x<8;x+=2)box(.025,.012,11.4,mat('#425354'),x,-.04,0);for(let z=-4;z<6;z+=2)box(16.4,.012,.025,mat('#425354'),0,-.04,z);
// Painted aisle guides.
const paint=mat('#ac945d');for(let z=-4;z<5;z+=.7){box(.07,.015,.35,paint,-1.15,-.035,z);box(.07,.015,.35,paint,1,-.035,z)}
const hits=[];function hit(g,type,index){g.traverse(o=>{if(o.isMesh){o.userData={type,index};hits.push(o)}})}
const crops={corn:{name:'Maïs',price:6,time:22,value:24,color:'#cfb657'},barley:{name:'Orge',price:9,time:30,value:31,color:'#b79a57'},grape:{name:'Raisin',price:13,time:40,value:42,color:'#7d528e'}};
let state={money:120,sold:0,inventory:{corn:0,barley:0,grape:0},mash:[],bottles:[],ferment:null,still:null,upgrade:false,expanded:false};let selected=null,audio=null,soundOn=false;const beds=[],plantGroups=[];
const buildPlant=buildDetailedPlant;
for(let i=0;i<6;i++){let x=-6.05+(i%2)*2.95,z=-3.1+Math.floor(i/2)*2.9,g=group(x,0,z);box(2.15,.4,2.13,M.wood,0,.17,0,g);box(1.95,.12,1.92,M.soil,0,.4,0,g);for(let a of [-1.05,1.05]){box(.09,.53,2.2,M.metal,a,.23,0,g);box(2.15,.07,.07,M.metal,0,.28,a,g)}let pg=new T.Group();g.add(pg);plantGroups.push(pg);beds.push({g,type:null,watered:false,start:0,locked:i>=4});hit(g,'bed',i);if(i>=4){box(2.05,.055,.17,M.black,0,.46,0,g).rotation.y=.75;box(2.05,.055,.17,M.black,0,.46,0,g).rotation.y=-.75}}
textSprite('01 / CULTURES',-4.55,.6,4.75,'#9ac7b2',.73);
const fermentGroup=group(2,0,-3.5);for(let x of [-.65,.65]){cyl(.53,.53,1.65,M.blue,x,.85,0,fermentGroup);for(let y of [.2,.6,1.15,1.55])cyl(.545,.545,.07,M.dark,x,y,0,fermentGroup);cyl(.49,.49,.09,M.metal,x,1.7,0,fermentGroup);pipe([[x,1.73,0],[x,2.06,0],[x+.18,2.06,0],[x+.18,1.89,0]],.034,M.metal,fermentGroup);box(.43,.38,.04,mat('#e3dfbf'),x,.95,.532,fermentGroup)}hit(fermentGroup,'ferment');textSprite('02 / FERMENTATION',2,2.7,-3.5,'#a6bec5',.62);
const stillGroup=group(5.7,0,-2.3);for(let x of [-.62,.62])for(let z of [-.5,.5])box(.12,.65,.12,M.dark,x,.33,z,stillGroup);cyl(.8,.8,.16,M.dark,0,.55,0,stillGroup);let boiler=sphere(.86,M.copper,0,1.37,0,stillGroup);boiler.scale.y=1.13;cyl(.22,.73,.8,M.copper,0,2.12,0,stillGroup);cyl(.16,.22,.45,M.copper,0,2.7,0,stillGroup);pipe([[0,2.9,0],[0,3.25,0],[.7,3.25,0],[1,2.7,0],[1,1.7,.1]],.075,M.copper,stillGroup);
let pts=[];for(let i=0;i<=100;i++){let a=i/100*Math.PI*10;pts.push([1+Math.cos(a)*.25,2.4-i/100*1.6,.2+Math.sin(a)*.25])}pipe(pts,.037,M.copper,stillGroup);cyl(.28,.32,.5,M.metal,1,.28,.2,stillGroup);const flame=sphere(.34,new T.MeshStandardMaterial({color:0xff8e24,emissive:0xff5511,emissiveIntensity:2}),0,.61,0,stillGroup);flame.scale.y=.3;const fire=new T.PointLight(0xff862e,4,4);fire.position.set(5.7,.65,-2.3);scene.add(fire);let gauge=cyl(.14,.14,.05,mat('#ece2c4'),0,1.85,.7,stillGroup);gauge.rotation.x=Math.PI/2;hit(stillGroup,'still');textSprite('03 / ALAMBIC',5.6,3.75,-2.2,'#d6ae7d',.7);
function bottle(x,y,z,p){let g=new T.Group();g.position.set(x,y,z);p.add(g);cyl(.09,.105,.34,M.glass,0,.17,0,g);cyl(.035,.07,.12,M.glass,0,.4,0,g);cyl(.037,.037,.07,M.gold,0,.49,0,g);box(.13,.14,.013,mat('#d9c6a2'),0,.2,.093,g);return g}
const sellGroup=group(5.15,0,3.1);box(3,.17,1.45,M.wood,0,1,0,sellGroup);for(let x of [-1.3,1.3])for(let z of [-.58,.58])box(.1,1,.1,M.dark,x,.45,z,sellGroup);box(1.2,.55,.8,M.wood,.7,1.35,0,sellGroup);for(let x=0;x<4;x++)bottle(-1.05+x*.28,1.09,.23,sellGroup);box(.6,.09,.4,M.black,-.6,1.13,-.35,sellGroup);hit(sellGroup,'sell');textSprite('04 / EXPÉDITION',5.1,2.15,3.3,'#d8c49e',.72);
// Storage wall, barrels, bags and irrigation.
for(let i=0;i<3;i++){let g=group(-7.45+i*.95,0,-4.7);sphere(.38,mat('#9a9378'),0,.42,0,g).scale.set(1,1.3,.8);cyl(.17,.2,.14,M.wood,0,.89,0,g)}
for(let z of [1,2.05]){let g=group(7.2,0,z);cyl(.42,.4,.95,M.wood,0,.49,0,g);for(let y of [.15,.77])cyl(.43,.43,.07,M.dark,0,y,0,g)}
pipe([[-7.9,.2,4.4],[-7.9,.2,-4.2],[-7.9,1,-4.6],[-7.9,1.4,-5.5]],.055,M.metal);box(.6,.8,.25,M.dark,-7.8,1.9,-4.8);neon(-7.8,2.1,-4.62,.25,0x84ffd0);
let dustGeo=new T.BufferGeometry(),positions=new Float32Array(150*3);for(let i=0;i<150;i++){positions[i*3]=(Math.random()-.5)*17;positions[i*3+1]=Math.random()*6;positions[i*3+2]=(Math.random()-.5)*12}dustGeo.setAttribute('position',new T.BufferAttribute(positions,3));let dust=new T.Points(dustGeo,new T.PointsMaterial({size:.025,color:'#b4d3c4',transparent:true,opacity:.4}));scene.add(dust);
const particles=[];function burst(x,z,color){for(let i=0;i<15;i++){let p=sphere(.045,mat(color),x,.8,z);particles.push({p,v:new T.Vector3((Math.random()-.5)*2,2+Math.random(),(Math.random()-.5)*2),life:1})}}
function beep(kind=0){sounds.action(kind===1?'complete':'click')}
function enableSound(){soundOn=sounds.enable(true);$('#sound').textContent=soundOn?'SON ON':'SON OFF';$('#sound').setAttribute('aria-label',soundOn?'Couper les bruitages':'Activer les bruitages')}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function ready(b){return b.type&&b.watered&&(Date.now()-b.start)/1000>=(b.duration||crops[b.type].time)}function progress(b){return !b.type?0:!b.watered?.13:Math.min(1,.13+(Date.now()-b.start)/1000/(b.duration||crops[b.type].time)*.87)}
function choose(type,index){if(type==='garden'){index=beds.findIndex(b=>!b.locked&&ready(b));if(index<0)index=beds.findIndex(b=>!b.locked&&!b.type);if(index<0)index=0;type='bed'}selected={type,index};document.body.classList.add('menu-open');$('#panel').classList.toggle('shop-panel',type==='shop');navigation?.panelOpened();$('#panel').classList.add('open');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('selected',b.dataset.select===(type==='bed'?'garden':type)));renderPanel();beep()}
function button(text,action,disabled=false,cls='primary'){return `<button class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`}
function renderPanel(){if(!selected||panelPointerDown)return;if(['farm','age','contracts','journal'].includes(selected.type)){renderCareerPanel();return;}if(['ferment','still','shop'].includes(selected.type)){renderEquipmentPanel();return;}let {type,index}=selected;let desc='',title='',body='',tag='';if(type==='bed'){let b=beds[index];tag=`CULTURES / BAC ${String(index+1).padStart(2,'0')}`;if(b.locked){title='Agrandir le jardin';desc='Débloquez deux bacs supplémentaires pour cultiver plus à chaque cycle.';body=button('Débloquer les 2 bacs · 90 $','expand',state.money<90)}else if(!b.type){title='Tout commence ici.';desc=`Choisissez une culture. Chaque bac donne ${career?.data.soil?4:3} récoltes.`;for(let [key,c]of Object.entries(crops))body+=button(`${c.name} <small>${career.growTime(key)} s · ${c.price} $</small>`,'plant:'+key,state.money<c.price,'choice')}else{let c=crops[b.type];title=c.name;desc=ready(b)?'Votre récolte est prête. Récupérez-la pour préparer votre prochain lot.':!b.watered?'Les graines sont en terre. Un peu d’eau pour lancer la croissance.':'Vos plantes grandissent. Préparez les autres bacs pendant ce temps.';body=`<div class="progress"><div style="width:${progress(b)*100}%"></div></div><div class="status">${ready(b)?'Prêt à récolter · +'+(b.yield||3)+' '+c.name:!b.watered?'En attente d’arrosage':Math.max(0,Math.ceil((b.duration||c.time)-(Date.now()-b.start)/1000))+' secondes restantes'}</div>`+button(ready(b)?'Récolter +'+(b.yield||3):!b.watered?'Arroser le bac':'Croissance en cours',ready(b)?'harvest':'water',b.watered&&!ready(b))}}else{tag='ATELIER / 04';title='Prêt pour le départ.';let val=state.bottles.reduce((a,k)=>a+crops[k].value,0)+(career?.data.aged||[]).reduce((a,k)=>a+Math.round(crops[k].value*1.5),0);desc='Expédiez votre production. Le maïs vaut 24 $, l’orge 31 $ et le raisin 42 $ par bouteille.';body=`<p class="status">${state.bottles.length} bouteilles + ${career?.data.aged.length||0} vieillies · ${val} $</p>`+button(`Vendre la production · +${val} $`,'sell',!state.bottles.length&&!career?.data.aged.length)+`<p class="status">${state.sold} / 12 bouteilles vendues</p>`}$('#ptype').textContent=tag;$('#ptitle').textContent=title;$('#pdesc').textContent=desc;setPanelBody(body)}
function jobUI(job,label){let p=Math.min(100,(Date.now()-job.start)/job.duration*100);return `<div class="progress"><div style="width:${p}%"></div></div><div class="status">${label} · ${Math.max(0,Math.ceil((job.duration-Date.now()+job.start)/1000))} s</div>`}
function updateHUD(){$('#money').textContent=state.money+' $';$('#bottles').innerHTML=(state.bottles.length+(career?.data.aged.length||0))+' <i>en stock</i>';for(let k of Object.keys(crops))$('#'+k).textContent=state.inventory[k];$('#mash').textContent=state.mash.length;const levels=[12,36,72,150,300,600];const next=levels.find(n=>n>state.sold)||Math.ceil((state.sold+1)/300)*300;$('#goalbar').style.width=Math.min(state.sold/next,1)*100+'%';$('#goaltext').textContent=state.sold+' / '+next+' bouteilles vendues · prochain palier';$('#rank').textContent=['APPRENTI','ARTISAN','DISTILLATEUR','MAÎTRE DE CHAI','MAISON RÉPUTÉE','GRANDE DISTILLERIE'][Math.min(5,levels.filter(n=>state.sold>=n).length)];let stage=state.bottles.length?2:state.mash.length||state.still||state.ferment||Object.values(state.inventory).some(n=>n>=3)?1:0;for(let i=0;i<3;i++)$('#s'+i).classList.toggle('active',stage===i);$('#objective').textContent=state.sold>=12?'La distillerie tourne. À vous de développer la suite.':stage===2?'Vos bouteilles sont prêtes à être vendues.':stage===1?'Transformez vos récoltes dans les ateliers.':beds.some(b=>b.type)?'Arrosez vos bacs, puis récoltez à maturité.':'Plantez vos premières graines.'}
$('#pbody').addEventListener('pointerdown',()=>panelPointerDown=true);addEventListener('pointerup',()=>panelPointerDown=false);addEventListener('pointercancel',()=>panelPointerDown=false);
$('#pbody').addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled||!selected)return;const parts=el.dataset.action.split(':'),[a,k]=parts;let success=false,keepOpen=false;
 if(a.startsWith('eq')){success=handleEquipment(parts);if(success)finishAction();else renderPanel();return}
 if(a==='career'){success=career.action(k);if(success)finishAction();return}
 if(a==='open'){choose(k);return}
 const b=selected.type==='bed'?beds[selected.index]:null;
 if(a==='plant'&&b&&!b.type&&crops[k]&&state.money>=crops[k].price){state.money-=crops[k].price;b.type=k;b.watered=false;b.start=0;b.duration=career.growTime(k);b.yield=career.data.soil?4:3;for(let x of [-.58,0,.58])for(let z of [-.57,0,.57])buildPlant(k,x,z,plantGroups[selected.index]);if(career.data.irrigation)career.water(b);else keepOpen=true;toast(crops[k].name+(b.watered?' planté et arrosé automatiquement.':' planté. Arrosez le bac.'));success=true}
 else if(a==='water'&&b&&b.type&&!b.watered){career.water(b);burst(b.g.position.x,b.g.position.z,'#68bada');toast('Bac arrosé. La croissance commence.');success=true}
 else if(a==='harvest'&&b&&ready(b)){const amount=b.yield||3;state.inventory[b.type]+=amount;toast('+'+amount+' '+crops[b.type].name+' dans vos réserves');b.type=null;const pg=plantGroups[selected.index];while(pg.children.length)disposePlant(pg.children[0]);burst(b.g.position.x,b.g.position.z,'#d8b867');success=true}
 else if(a==='sell'&&(state.bottles.length||career.data.aged.length)){let amount=state.bottles.reduce((a,k)=>a+crops[k].value,0);state.money+=amount;state.sold+=state.bottles.length;state.bottles=[];amount+=career.sellAged();toast('Production vendue · +'+amount+' $');burst(5,3,'#e9be68');success=true}
 else if(a==='expand'&&state.money>=90&&!state.expanded){state.money-=90;state.expanded=true;beds.slice(4).forEach(b=>{b.locked=false;b.g.children.filter(o=>o.material===M.black).forEach(o=>b.g.remove(o))});toast('Deux nouveaux bacs sont disponibles.');success=true}
 if(success){sounds.action(a);career.save();updateHUD();if(!keepOpen)finishAction();else renderPanel()}
});
production=createProduction(state,toast,name=>sounds.action(name));
const workshop=improveWorkshop({T,scene,M,box,cyl,sphere,pipe,mesh,fermentGroup,stillGroup,sellGroup,flame,beds,hit,hits});
expansion=expandWorkshop({scene,M,mesh,box,cyl,sphere,pipe,group,textSprite,fermentGroup,stillGroup,roots:workshop.roots,production});
estate=buildEstate({scene,M,mesh,box,cyl,sphere,pipe,group,roots:workshop.roots,beds,fermentGroup,stillGroup,sellGroup});
career=createCareer({state,production,beds,crops,notify:toast,fx:name=>sounds.action(name)});
if(career.restore()){beds.forEach((b,i)=>{if(b.type)for(let x of [-.58,0,.58])for(let z of [-.57,0,.57])buildPlant(b.type,x,z,plantGroups[i]);if(!b.locked)b.g.children.filter(o=>o.material===M.black).forEach(o=>b.g.remove(o))});toast('Votre distillerie a été restaurée.')}production.tick();expansion.update();estate.update('walk',career.data);
$('#shop').onclick=()=>choose('shop');$('#journal').onclick=()=>choose('journal');
addEventListener('pagehide',()=>career.save());

$('#openfull').href=window.location.href;
function closePanel(){document.body.classList.remove('menu-open');$('#panel').classList.remove('open');selected=null;document.querySelectorAll('nav button').forEach(b=>b.classList.remove('selected'));navigation?.panelClosed()}
for(let b of document.querySelectorAll('[data-select]'))b.onclick=()=>choose(b.dataset.select);
$('#close').onclick=()=>{closePanel();if(navigation?.mode==='walk')navigation.resume()};
$('#sound').onclick=()=>{if(soundOn){soundOn=false;sounds.enable(false);$('#sound').textContent='SON OFF';$('#sound').setAttribute('aria-label','Activer les bruitages')}else enableSound()};
$('#help').onclick=()=>{navigation?.pause();$('#guide').showModal()};
$('#start').onclick=()=>{$('#guide').close();if(navigation?.mode==='walk')navigation.resume()};
$('#resetcam').onclick=()=>{azimuth=.76;elevation=.77;distance=34;cam()};
$('#zoomplus').onclick=()=>{distance=Math.max(14,distance-2);cam()};
$('#zoomminus').onclick=()=>{distance=Math.min(38,distance+2);cam()};
navigation=createNavigation({camera,canvas,scene,beds,roots:workshop.roots,fullColliders:estate.colliders,occluders:estate.occluders,orbit:cam,choose,closePanel,hasPanel:()=>!!selected,audioStart:()=>{if(!soundStarted){enableSound();soundStarted=true}},footstep:()=>sounds.action('step')});
let soundStarted=false;
const ray=new T.Raycaster(),pointer=new T.Vector2();let drag=null;
canvas.addEventListener('pointerdown',e=>{if(navigation.mode!=='overview')return;drag={x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(navigation.mode!=='overview')return;if(drag){if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)drag.moved=true;if(drag.moved){azimuth-=(e.clientX-drag.px)*.007;elevation=Math.max(.3,Math.min(1.35,elevation+(e.clientY-drag.py)*.005));cam()}drag.px=e.clientX;drag.py=e.clientY}else{pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);canvas.style.cursor=ray.intersectObjects(workshop.roots,true).length?'pointer':'grab'}});
canvas.addEventListener('pointerup',e=>{if(navigation.mode!=='overview')return;if(drag&&!drag.moved){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);let h=ray.intersectObjects(workshop.roots,true)[0];if(h){let o=h.object;while(o&&!o.userData.type)o=o.parent;if(o)choose(o.userData.type,o.userData.index)}}drag=null});
canvas.addEventListener('pointercancel',()=>drag=null);
canvas.addEventListener('wheel',e=>{if(navigation.mode!=='overview')return;e.preventDefault();distance=Math.max(14,Math.min(38,distance+e.deltaY*.02));cam()},{passive:false});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
addEventListener('keydown',e=>{if(navigation.mode!=='overview')return;let n=Number(e.key);if(n>=1&&n<=4)choose(['garden','ferment','still','sell'][n-1]);if(e.key==='Escape')closePanel()});
let last=performance.now(),lastUI=0;function animate(now){requestAnimationFrame(animate);let dt=Math.min((now-last)/1000,.05);last=now;let t=now*.001;navigation.update(dt,t);estate.update(navigation.mode,career.data,production,t);drawMap();workshop.update(t,{...state,still:!!production.units.still[0].job&&!production.progress(production.units.still[0]).ready},navigation.mode);sounds.update(state,camera.position,t);for(let i=0;i<beds.length;i++){let b=beds[i],pg=plantGroups[i];for(let plant of pg.children){let s=progress(b);plant.scale.setScalar(s);plant.rotation.z=Math.sin(t*1.4+plant.position.x+i)*.025*s}}flame.visible=!!production.units.still[0].job&&!production.progress(production.units.still[0]).ready;fire.intensity=flame.visible?5+Math.sin(t*15)*1:0;flame.scale.set(.9+Math.sin(t*12)*.1,.3,1);dust.rotation.y=Math.sin(t*.04)*.03;for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.v.y-=dt*4;p.p.position.addScaledVector(p.v,dt);p.p.scale.setScalar(Math.max(.01,p.life));if(p.life<=0){scene.remove(p.p);p.p.geometry.dispose();p.p.material.dispose();particles.splice(i,1)}}if(now-lastUI>250){lastUI=now;production.tick();career.tick();expansion.update();if(now-saveTimer>5000){career.save();saveTimer=now}updateHUD();if(selected)renderPanel()}renderer.render(scene,camera)}updateHUD();requestAnimationFrame(animate);

function setPanelBody(body){if(panelHTML!==body){$('#pbody').innerHTML=body;panelHTML=body}}
function finishAction(){production.tick();expansion.update();career.save();updateHUD();closePanel();if(navigation?.mode==='walk')navigation.resume()}
function handleEquipment([a,kind,index,arg]){const i=Number(index);if(a==='eqview'){choose(kind,i);return false}let ok=false;if(a==='eqbuy')ok=production.buy(kind,i);else if(a==='equpgrade')ok=production.upgrade(kind,i);else if(a==='eqstart')ok=production.start(kind,i,arg);else if(a==='eqcollect')ok=production.collect(kind,i);production.tick();expansion.update();return ok}
function renderEquipmentPanel(){let kind=selected.type,i=selected.index||0,title,desc,body='',tag;if(kind==='shop'){tag='ÉQUIPEMENT / BOUTIQUE';title='Agrandissez la production.';desc='Les achats installent de nouvelles machines dans les ateliers. Chaque machine travaille indépendamment.';body=button('Améliorations de la serre','open:farm',false,'secondary');for(let category of ['ferment','still']){body+='<h3>'+ (category==='ferment'?'Cuves de fermentation':'Alambics')+'</h3>';production.units[category].forEach((u,j)=>{const st=production.stats(category,j);body+='<div class="equipment-card"><strong>'+u.name+'</strong><small>'+st.capacity+' unités / lot · '+st.seconds+' s</small>'+button(u.owned?'Ouvrir la machine':'Acheter · '+u.cost+' $',(u.owned?'eqview:':'eqbuy:')+category+':'+j,!u.owned&&state.money<u.cost,'secondary')+'</div>'})}}else{const u=production.units[kind][i],st=production.stats(kind,i),p=production.progress(u);tag=(kind==='ferment'?'FERMENTATION':'DISTILLATION')+' / '+String(i+1).padStart(2,'0');title=u.name;desc='Jusqu’à '+st.capacity+' unités par lot · '+st.seconds+' secondes · minimum 3 unités.';body='<div class="machine-tabs">'+production.units[kind].map((v,j)=>button(String(j+1)+(v.owned?'':' · $'),'eqview:'+kind+':'+j,false,j===i?'tab active':'tab')).join('')+'</div>';if(!u.owned)body+='<p>Une machine plus productive, installée dans son atelier.</p>'+button('Acheter · '+u.cost+' $','eqbuy:'+kind+':'+i,state.money<u.cost);else if(u.job){body+='<div class="progress"><div style="width:'+p.percent+'%"></div></div><p class="status">'+p.percent+' % · '+(p.ready?'Lot terminé':p.remaining+' secondes restantes')+'</p><p>'+u.job.types.length+' unités en cours</p>'+button('Récupérer '+u.job.types.length+(kind==='ferment'?' moûts':' bouteilles'),'eqcollect:'+kind+':'+i,!p.ready)}else{if(kind==='ferment')for(let [crop,c]of Object.entries(crops)){let count=Math.min(st.capacity,state.inventory[crop]);body+=button(c.name+' <small>'+count+' unités · '+state.inventory[crop]+' en réserve</small>','eqstart:'+kind+':'+i+':'+crop,count<3,'choice')}else{let count=Math.min(st.capacity,state.mash.length);body+=button('Distiller '+count+' moûts','eqstart:'+kind+':'+i,count<3);body+='<p class="status">'+state.mash.length+' moûts en réserve</p>'}body+=u.upgraded?'<p class="status">Vitesse améliorée ×2</p>':button('Améliorer la vitesse ×2 · '+(100+i*80)+' $','equpgrade:'+kind+':'+i,state.money<100+i*80,'secondary')}}$('#ptype').textContent=tag;$('#ptitle').textContent=title;$('#pdesc').textContent=desc;$('#panel').classList.toggle('shop-panel',kind==='shop');setPanelBody(body)}

function renderCareerPanel(){const type=selected.type,d=career.data;let title='',desc='',body='';if(type==='farm'){title='Une serre plus productive.';desc='Les améliorations s’appliquent aux nouvelles plantations.';body=button(d.irrigation?'Irrigation installée':'Irrigation automatique · 180 $','career:irrigation',d.irrigation||state.money<180)+ '<p class="status">Arrose à la plantation · croissance 20 % plus rapide</p>'+button(d.soil?'Terreau enrichi installé':'Terreau enrichi · 120 $','career:soil',d.soil||state.money<120)+'<p class="status">4 récoltes par bac au lieu de 3</p>';if(!state.expanded)body+=button('Débloquer deux bacs · 90 $','expand',state.money<90,'secondary')}
else if(type==='age'){title='Le temps fait la différence.';desc='Placez 3 à 6 bouteilles dans les fûts pendant 45 secondes. Leur valeur de vente augmente de 50 %.';if(d.ageJob){const p=career.ageProgress();body='<div class="progress"><div style="width:'+p.percent+'%"></div></div><p class="status">'+p.percent+' % · '+p.remaining+' s · '+d.ageJob.types.length+' bouteilles</p>'+button('Récupérer les bouteilles vieillies','career:ageCollect',!p.ready)}else body=button('Mettre en fût '+Math.min(6,state.bottles.length)+' bouteilles','career:ageStart',state.bottles.length<3);body+='<p class="status">'+d.aged.length+' bouteilles vieillies en réserve</p>'}
else if(type==='contracts'){const c=career.contract(),n=state.bottles.filter(k=>k===c.type).length;title=c.name;desc='Commande n° '+(d.contracts+1)+' · bonus de 45 % par rapport à la vente directe.';body='<div class="equipment-card"><strong>'+c.quantity+' bouteilles à base de '+crops[c.type].name.toLowerCase()+'</strong><small>'+n+' disponibles · bouteilles non vieillies</small><p class="status">Récompense : '+c.reward+' $</p></div>'+button('Livrer la commande','career:contract',n<c.quantity)+'<p>'+d.contracts+' commandes honorées</p>'}
else{title='Votre maison grandit.';desc='Cultivez, produisez, faites vieillir et livrez des commandes pour financer votre atelier.';body='<div class="equipment-card"><strong>'+$('#rank').textContent+'</strong><small>'+state.sold+' bouteilles vendues · '+d.contracts+' commandes livrées</small></div>'+button('Améliorer la serre','open:farm',false,'secondary')+button('Consulter la commande client','open:contracts',false,'secondary')+button('Gérer le vieillissement','open:age',false,'secondary')+'<p class="status">Sauvegarde automatique sur ce navigateur. Les lots continuent pendant votre absence.</p>'}$('#ptype').textContent={farm:'SERRE / AMÉLIORATIONS',age:'CHAI / VIEILLISSEMENT',contracts:'EXPÉDITION / COMMANDES',journal:'CARNET / PROGRESSION'}[type];$('#ptitle').textContent=title;$('#pdesc').textContent=desc;setPanelBody(body)}
function drawMap(){const c=$('#minimap'),ctx=c.getContext('2d'),sx=x=>12+(x+8.4)/25.3*226,sz=z=>12+(z+5.9)/11.8*106;ctx.fillStyle='#10232a';ctx.fillRect(0,0,250,130);ctx.strokeStyle='#64827f';ctx.lineWidth=1;ctx.strokeRect(12,12,226,106);ctx.fillStyle='#254a3a';ctx.fillRect(12,12,62,106);ctx.fillStyle='#23424d';ctx.fillRect(76,12,100,65);ctx.fillStyle='#514332';ctx.fillRect(177,12,61,65);ctx.fillStyle='#b3c9c5';ctx.font='10px sans-serif';ctx.fillText('SERRE',23,29);ctx.fillText('CUVES',108,29);ctx.fillText('ALAMBICS',180,29);ctx.fillText('EXPÉDITION',106,110);ctx.fillStyle='#aac1b0';for(const b of beds)ctx.fillRect(sx(b.g.position.x)-6,sz(b.g.position.z)-6,12,12);for(const kind of ['ferment','still'])estate.machinePositions[kind].forEach(([x,z],i)=>{ctx.fillStyle=production.units[kind][i].owned?'#dbbb7e':'#536264';ctx.fillRect(sx(x)-5,sz(z)-5,10,10)});if(navigation?.mode==='walk'){const p=navigation.position,dir=new T.Vector3();camera.getWorldDirection(dir);ctx.strokeStyle='#fff4ca';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(sx(p.x),sz(p.z));ctx.lineTo(sx(p.x)+dir.x*10,sz(p.z)+dir.z*10);ctx.stroke();ctx.fillStyle='#fff4ca';ctx.beginPath();ctx.arc(sx(p.x),sz(p.z),3,0,Math.PI*2);ctx.fill()}}
