import * as T from './three.module.js';
export function createNavigation({camera,canvas,scene,beds,roots,orbit,choose,closePanel,hasPanel,audioStart,footstep,extraColliders=[],fullColliders=null,occluders=[]}){
 const $=s=>document.querySelector(s),keys=new Set(),pos=new T.Vector3(0,1.68,4.7),ray=new T.Raycaster();let mode='walk',yaw=0,pitch=-.08,active=false,focused=null,drag=null,stepDistance=0,lastPosition=pos.clone(),touchMove=new T.Vector2();const isTouch=()=>matchMedia('(pointer: coarse)').matches;
 let wantsCapture=false,requestSerial=0;
 const colliders=fullColliders||beds.map(b=>({x:b.g.position.x,z:b.g.position.z,w:2.15,d:2.13})).concat([{x:2,z:-3.5,w:2.45,d:1.2},{x:5.95,z:-2.3,w:2.5,d:2},{x:5.15,z:3.1,w:3.15,d:1.6},{x:7.2,z:1.5,w:1,d:2.1},{x:-6.5,z:-4.7,w:3,d:.85},{x:-7.8,z:-4.8,w:.7,d:.4}],extraColliders);
 function canOccupy(x,z){if(x< -7.72||x>16.55||z< -5.48||z>5.42)return false;const radius=.18;return !colliders.some(b=>{const dx=Math.max(Math.abs(x-b.x)-b.w/2,0),dz=Math.max(Math.abs(z-b.z)-b.d/2,0);return dx*dx+dz*dz<radius*radius})}
 function move(dx,dz){const steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/.06));for(let i=0;i<steps;i++){if(canOccupy(pos.x+dx/steps,pos.z))pos.x+=dx/steps;if(canOccupy(pos.x,pos.z+dz/steps))pos.z+=dz/steps}}
 function look(dx,dy){yaw-=dx*.0024;pitch=Math.max(-1.35,Math.min(1.3,pitch-dy*.0024))}
 function cameraWalk(bob=0){camera.position.copy(pos);camera.position.y+=bob;camera.rotation.order='YXZ';camera.rotation.set(pitch,yaw,0)}
 function drawGate(){const show=mode==='walk'&&!active&&!hasPanel();document.body.classList.toggle('playing',mode==='walk'&&active&&!hasPanel());$('#walkgate').hidden=!show;$('#reticle').hidden=mode!=='walk'||!active||hasPanel();$('#touchcontrols').hidden=mode!=='walk'||!isTouch()||hasPanel()||!active;if(!active)$('#interact').hidden=true}
 function unlock(){wantsCapture=false;requestSerial++;active=false;drag=null;keys.clear();if(document.pointerLockElement===canvas)document.exitPointerLock()}
 function setMode(value){unlock();mode=value;focused=null;document.body.classList.toggle('walking',mode==='walk');$('#viewmode').textContent=mode==='walk'?'Vue d’ensemble':'Explorer à pied';$('#viewmode').setAttribute('aria-pressed',String(mode==='walk'));camera.fov=mode==='walk'?72:39;camera.updateProjectionMatrix();if(mode==='walk')cameraWalk();else orbit();closePanel();drawGate()}
 function captureFailed(serial){if(serial!==requestSerial||mode!=='walk'||hasPanel()||document.pointerLockElement===canvas)return;wantsCapture=false;active=false;keys.clear();$('#captureerror').hidden=false;$('#captureerror').textContent='La souris n’a pas été capturée. Cliquez sur Réessayer. Si le jeu est intégré dans une autre page, ouvrez-le dans un onglet séparé.';$('#openfull').hidden=false;$('#resume').textContent='Réessayer la capture';drawGate()}
 async function resume(){if(mode!=='walk')setMode('walk');closePanel();audioStart();keys.clear();$('#captureerror').hidden=true;$('#openfull').hidden=true;$('#resume').textContent='Reprendre l’exploration';if(isTouch()){active=true;drawGate();return}wantsCapture=true;active=false;const serial=++requestSerial;drawGate();if(!canvas.requestPointerLock){captureFailed(serial);return}try{await canvas.requestPointerLock();if(serial===requestSerial&&document.pointerLockElement===canvas){active=true;drawGate()}}catch{captureFailed(serial)}}
 function pause(){unlock();touchMove.set(0,0);drawGate()}
 function interact(){if(mode!=='walk'||!active||hasPanel())return;if(focused){const object=focused;choose(object.type,object.index)}else if(isTouch())$('#walkstatus').textContent='Approchez-vous et visez un bac ou un atelier.'}
 function panelOpened(){unlock();touchMove.set(0,0);drawGate()}
 document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===canvas;if(locked&&(mode!=='walk'||hasPanel()||!wantsCapture)){document.exitPointerLock();return}active=locked&&mode==='walk'&&!hasPanel();if(!locked)wantsCapture=false;keys.clear();drawGate()});
 document.addEventListener('pointerlockerror',()=>captureFailed(requestSerial));
 document.addEventListener('mousemove',e=>{if(mode==='walk'&&active&&!hasPanel()&&document.pointerLockElement===canvas)look(e.movementX,e.movementY)});
 canvas.addEventListener('pointerdown',e=>{if(mode!=='walk')return;if(!active&&!hasPanel()){resume();return}if(isTouch()&&active&&!hasPanel()){drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)}});
 canvas.addEventListener('pointermove',e=>{if(isTouch()&&active&&!hasPanel()&&drag&&e.pointerId===drag.id){look((e.clientX-drag.x)*1.6,(e.clientY-drag.y)*1.6);drag.x=e.clientX;drag.y=e.clientY}});
 const end=()=>drag=null;canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
 addEventListener('keydown',e=>{if(mode!=='walk')return;const k=e.key.toLowerCase();if(['z','w','q','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift','e','escape'].includes(k)){if(k==='escape'){if(hasPanel()){closePanel();pause()}else pause();return}if(!active||hasPanel())return;e.preventDefault();keys.add(k);if(k==='e'&&!e.repeat)interact()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
 for(let b of document.querySelectorAll('[data-move]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.move)});for(let event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.move))}
 $('#touchinteract').onclick=interact;$('#resume').onclick=resume;$('#viewmode').onclick=()=>setMode(mode==='walk'?'overview':'walk');$('#overviewgate').onclick=()=>setMode('overview');
 function update(dt,time){if(mode!=='walk')return;const moving=active&&!hasPanel();let fw=(keys.has('z')||keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0),side=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('q')||keys.has('a')||keys.has('arrowleft')?1:0),len=Math.hypot(fw,side);lastPosition.copy(pos);if(moving&&len){fw/=len;side/=len;const speed=keys.has('shift')?4.2:2.5;move((Math.cos(yaw)*side-Math.sin(yaw)*fw)*dt*speed,(-Math.sin(yaw)*side-Math.cos(yaw)*fw)*dt*speed)}let traveled=pos.distanceTo(lastPosition);stepDistance+=traveled;if(stepDistance>.68){footstep();stepDistance=0}cameraWalk(traveled>.001?Math.sin(time*(keys.has('shift')?15:10))*.025:0);focused=null;if(moving){camera.updateMatrixWorld();scene.updateMatrixWorld();ray.setFromCamera(new T.Vector2(0,0),camera);const intersections=ray.intersectObjects([...roots,...occluders],true).filter(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent}return true});const h=intersections[0];if(h&&h.distance<3){let o=h.object;while(o&&!o.userData.type)o=o.parent;if(o)focused=o.userData}$('#interact').hidden=!focused;if(focused){let label=focused.type==='bed'?'Bac '+(focused.index+1):{ferment:'Cuve '+((focused.index||0)+1),still:'Alambic '+((focused.index||0)+1),sell:'Table d’expédition',farm:'Améliorations de la serre',age:'Chai de vieillissement',contracts:'Commandes clients'}[focused.type];$('#interactlabel').textContent=label}$('#reticle').classList.toggle('aimed',!!focused)}else $('#interact').hidden=true}
 setMode('walk');return {update,resume,pause,panelOpened,panelClosed:drawGate,setMode,get mode(){return mode},get position(){return pos},canOccupy,move,keys};
}
