export const catalog={ferment:[{name:'Cuves artisanales',cost:0,capacity:3,seconds:18},{name:'Cuve inox Pro',cost:160,capacity:6,seconds:14},{name:'Fermenteur industriel',cost:390,capacity:12,seconds:10}],still:[{name:'Alambic en cuivre',cost:0,capacity:3,seconds:24},{name:'Alambic à colonne',cost:260,capacity:6,seconds:16},{name:'Distillateur industriel',cost:650,capacity:12,seconds:10}]};
export function createProduction(state,notify,fx,clock=()=>Date.now()){
 const units={ferment:catalog.ferment.map((c,i)=>({...c,owned:i===0,job:null,upgraded:false})),still:catalog.still.map((c,i)=>({...c,owned:i===0,job:null,upgraded:false}))};
 function stats(kind,i){const u=units[kind]?.[i];if(!u)return null;return {...u,seconds:u.seconds*(u.upgraded?.5:1)}}
 function progress(u){if(!u.job)return {percent:0,remaining:0,ready:false};const remaining=Math.max(0,Math.ceil((u.job.start+u.job.duration-clock())/1000));return {percent:Math.min(100,Math.max(0,Math.floor((clock()-u.job.start)/u.job.duration*100))),remaining,ready:clock()>=u.job.start+u.job.duration}}
 function buy(kind,i){const u=units[kind]?.[i];if(!u||u.owned||state.money<u.cost)return false;state.money-=u.cost;u.owned=true;notify(u.name+' installé dans son atelier.');fx('upgrade');return true}
 function upgrade(kind,i){const u=units[kind]?.[i],cost=100+i*80;if(!u||!u.owned||u.upgraded||u.job||state.money<cost)return false;state.money-=cost;u.upgraded=true;notify(u.name+' : temps des prochains lots divisé par deux.');fx('upgrade');return true}
 function start(kind,i,crop){const u=units[kind]?.[i];if(!u?.owned||u.job)return false;const available=kind==='ferment'?(state.inventory[crop]||0):state.mash.length,count=Math.min(u.capacity,available);if(count<3)return false;let types;if(kind==='ferment'){state.inventory[crop]-=count;types=Array(count).fill(crop)}else types=state.mash.splice(0,count);u.job={types,start:clock(),duration:stats(kind,i).seconds*1000,notified:false};notify(u.name+' : lot de '+count+' lancé.');fx(kind==='ferment'?'ferment':'distill');return true}
 function collect(kind,i){const u=units[kind]?.[i];if(!u?.job||!progress(u).ready)return false;const count=u.job.types.length;(kind==='ferment'?state.mash:state.bottles).push(...u.job.types);u.job=null;notify('Lot récupéré · +'+count+(kind==='ferment'?' moûts':' bouteilles'));fx('complete');return true}
 function tick(){for(const [kind,list]of Object.entries(units))for(const u of list)if(u.job&&progress(u).ready&&!u.job.notified){u.job.notified=true;notify(u.name+' · 100 % · lot prêt à récupérer');fx('complete')}state.ferment=units.ferment.some(u=>u.job&&!progress(u).ready);state.still=units.still.some(u=>u.job&&!progress(u).ready)}
 return {units,stats,progress,buy,upgrade,start,collect,tick};
}
